# Reference: https://docs.docker.com/reference/compose-file/
name: minichat

services:
  scylla:
    command:
      - --seeds=minichat-scylla-1,minichat-scylla-2,minichat-scylla-3
      - --reactor-backend=epoll
      - --smp=1
    deploy:
      replicas: 4
    healthcheck:
      test: cqlsh -e "DESCRIBE CLUSTER"
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 15s
    # hostname: scylla  # Hostnames for replicas: {project name}-api-service-{replica number}, see [http.upstream] in services/api-proxy/nginx.conf
    image: scylladb/scylla:6.2
    mem_limit: 1gb

  data-service:
    build:
      context: .
      dockerfile: services/data/Dockerfile
    container_name: data-service
    depends_on:
      scylla:
        condition: service_healthy
    hostname: data-service

  api-service:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    depends_on:
      - data-service
    deploy:
      replicas: 2
    # hostname: api-service

  api-reverse-proxy:
    build:
      context: .
      dockerfile: services/api-proxy/Dockerfile
    container_name: api-reverse-proxy
    depends_on:
      - api-service
    ports:
      - "80:80"
