# Reference: https://docs.docker.com/reference/compose-file/
name: minichat

x-rabbitmq-default: &rabbitmq-default
  environment:
    - RABBITMQ_ERLANG_COOKIE=cluster_cookie
  healthcheck:
    test: rabbitmq-diagnostics -q status
    interval: 5s
    timeout: 5s
    retries: 20
    start_period: 15s
  image: custom-rabbitmq
  mem_limit: 1gb
  user: rabbitmq

services:
  scylla:
    command:
      - --memory=1G
      - --reactor-backend=epoll
      - --seeds=minichat-scylla-1,minichat-scylla-2,minichat-scylla-3
      - --smp=1
    deploy:
      replicas: 3
    healthcheck:
      test: cqlsh -e "DESCRIBE CLUSTER"
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 15s
    # hostname: scylla  # Hostnames for replicas: {project name}-api-service-{replica number}, see [http.upstream] in services/api-proxy/nginx.conf
    image: scylladb/scylla:6.2

  rabbitmq-1:
    build:
      context: .
      dockerfile: services/rabbitmq/Dockerfile
    container_name: rabbitmq-1
    hostname: rabbitmq-1
    <<: *rabbitmq-default

  rabbitmq-2:
    container_name: rabbitmq-2
    hostname: rabbitmq-2
    <<: *rabbitmq-default

  rabbitmq-3:
    container_name: rabbitmq-3
    hostname: rabbitmq-3
    <<: *rabbitmq-default

  rabbitmq-proxy:
    build:
      context: .
      dockerfile: services/rabbitmq-proxy/Dockerfile
    container_name: rabbitmq-proxy
    depends_on:
      rabbitmq-1:
        condition: service_healthy
      rabbitmq-2:
        condition: service_healthy
      rabbitmq-3:
        condition: service_healthy
    hostname: rabbitmq-proxy

  data-service:
    build:
      context: .
      dockerfile: services/data/Dockerfile
    command:
      - --host=0.0.0.0
      - --port=16000
      - --scylla-hosts=minichat-scylla-1,minichat-scylla-2,minichat-scylla-3
      - --amqp-host=amqp://guest:guest@rabbitmq-proxy:5672
    container_name: data-service
    depends_on:
      scylla:
        condition: service_healthy
      rabbitmq-proxy:
        condition: service_started
    hostname: data-service

  api-service:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    command:
      - --host=0.0.0.0
      - --port=8000
      - --data-service=data-service:16000
      - --amqp-host=amqp://guest:guest@rabbitmq-proxy:5672
    depends_on:
      - data-service
    deploy:
      replicas: 2
    # hostname: api-service

  api-proxy:
    build:
      context: .
      dockerfile: services/api-proxy/Dockerfile
    container_name: api-proxy
    depends_on:
      - api-service
    ports:
      - "8000:8000"

  frontend:
    build:
      args:
        VITE_APP_BASE_API_URL: localhost:8000
      context: .
      dockerfile: services/frontend/Dockerfile
    container_name: frontend
    depends_on:
      - api-proxy
    ports:
      - "80:80"
