# Reference: https://docs.docker.com/reference/compose-file/
name: minichat-dev

services:
  scylla:
    command:
      - --overprovisioned=1
      - --reactor-backend=epoll
      - --seeds=scylla1,scylla2,scylla3
      - --smp=1
    deploy:
      replicas: 4
    healthcheck:
      test: cqlsh -e "DESCRIBE CLUSTER"
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 15s
    # hostname: scylla  # Hostnames for replicas: {project name}-api-service-{replica number}, see [http.upstream] in services/api-proxy/nginx.conf
    image: scylladb/scylla:6.2
    mem_limit: 1gb

  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: devcontainer
    extra_hosts:
      data-service: "127.0.0.1"
    ports:
      - "8000:8000"
    volumes:
      - ..:/workspaces/minichat
    command: bash -c "services/api/scripts/compile.sh && sleep infinity"
    working_dir: /workspaces/minichat
