# Reference: https://docs.docker.com/reference/compose-file/
name: minichat

x-rabbitmq-default: &rabbitmq-default
  cpus: 1.00
  environment:
    - RABBITMQ_ERLANG_COOKIE=cluster_cookie
  healthcheck:
    test: rabbitmq-diagnostics -q status
    interval: 5s
    timeout: 5s
    retries: 20
    start_period: 15s
  image: custom-rabbitmq
  mem_limit: 1gb
  user: rabbitmq

services:
  scylla:
    command:
      - --memory=1G
      - --overprovisioned=1
      - --reactor-backend=epoll
      - --seeds=minichat-scylla-1,minichat-scylla-2,minichat-scylla-3
      - --smp=1
    deploy:
      replicas: 3
    healthcheck:
      test: cqlsh -e "DESCRIBE CLUSTER"
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 15s
    # hostname: scylla  # Hostnames for replicas: {project name}-api-service-{replica number}, see [http.upstream] in services/api-proxy/nginx.conf
    image: scylladb/scylla:6.2

  rabbitmq-1:
    build:
      context: ..
      dockerfile: services/rabbitmq/Dockerfile
    container_name: rabbitmq-1
    hostname: rabbitmq-1
    <<: *rabbitmq-default

  rabbitmq-2:
    container_name: rabbitmq-2
    hostname: rabbitmq-2
    <<: *rabbitmq-default

  rabbitmq-3:
    container_name: rabbitmq-3
    hostname: rabbitmq-3
    <<: *rabbitmq-default

  rabbitmq-proxy:
    build:
      context: ..
      dockerfile: services/rabbitmq-proxy/Dockerfile
    container_name: rabbitmq-proxy
    depends_on:
      rabbitmq-1:
        condition: service_healthy
      rabbitmq-2:
        condition: service_healthy
      rabbitmq-3:
        condition: service_healthy
    hostname: rabbitmq-proxy
    ports:
      - "1936:1936"

  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: bash -c "services/api/scripts/compile.sh && sleep infinity"
    container_name: devcontainer
    cpus: 4.00
    depends_on:
      scylla:
        condition: service_healthy
      rabbitmq-proxy:
        condition: service_started
    environment:
      - VUE_APP_BASE_API_URL=http://localhost:8000
    ports:
      - "5173:5173" # frontend (vite)
      - "8000:8000" # api (uvicorn)
    volumes:
      - ..:/workspaces/minichat
    working_dir: /workspaces/minichat
